DATA:
  USE_MOTION: True
  SIZE: 456
  TRAIN_JSON_PATH: "your-path-to-data/train_nlpaug.json"
  EVAL_JSON_PATH: "your-path-to-data/val_nlpaug.json"
  CROP_AREA: 1.6666667 ## new_w = CROP_AREA* old_w
 


MODEL:
  NAME: "dual-stream-v2"
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "efficientnet-b3"
  car_idloss: False
  mo_idloss: False
  share_idloss: False
  HEAD:
    CLIP_LOSS_MARGIN: 0.
    CLS_NONLINEAR: True
    CLS_LOSS_SCALE: 48
    CLS_LOSS_MARGIN: 0.35
    CAR_CLS: 'Linear'
    MO_CLS: 'Linear'
    SHARED_CLS: 'Linear'
  METRIC:
    METRIC_WEIGHT: 1.
    LOSS: 'CircleLoss'
    LOSS_SCALE: 80
    LOSS_MARGIN: 0.4
TRAIN: 
  BATCH_SIZE: 80

TEST:
  QUERY_JSON_PATH: "your-path-to-data/test-queries_nlpaug.json"
  RESTORE_FROM: "checkpoints/circle_loss.pth"

