DATA:
  USE_MOTION: True
  SIZE: 456
  TRAIN_JSON_PATH: "your-path-to-data/train_nlpaug_3.json"
  EVAL_JSON_PATH: "your-path-to-data/val_nlpaug_3.json"
  CROP_AREA: 1.6666667 ## new_w = CROP_AREA* old_w
 


MODEL:
  NAME: "dual-text-cat"
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "efficientnet-b3"
  car_idloss: False
  mo_idloss: False
  share_idloss: False
  SAME_TEXT: True
  MERGE_DIM: 1024
TRAIN: 
  BATCH_SIZE: 80

TEST:
  QUERY_JSON_PATH: "your-path-to-data/test-queries_nlpaug_3.json"
  RESTORE_FROM: "checkpoints/dual_baseline_aug3.pth"

