DATA:
  USE_MOTION: True
  SIZE: 456
  TRAIN_JSON_PATH: "your-path-to-data/train-tracks_nlpaug.json"
  EVAL_JSON_PATH: "your-path-to-data/val_nlpaug.json"
  CROP_AREA: 1.6666667 ## new_w = CROP_AREA* old_w
 


MODEL:
  NAME: "dual-stream-v2"
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "efficientnet-b3"
  car_idloss: False
  mo_idloss: False
  share_idloss: False
TRAIN: 
  BATCH_SIZE: 80

TEST:
  QUERY_JSON_PATH: "your-path-to-data/test-queries_nlpaug.json"
  RESTORE_FROM: "checkpoints/single_baseline_aug1_plus.pth"

